language: python

python:
  - "2.7"
  - "3.5"
  - "3.6"

install:
  - bash travis/install_pytorch.sh
  - pip install .

script: pytest

deploy:
  provider: pypi
  user: kchen
  password:
    secure: VLaJH6buurJJRVVSiya/yy65oBppF7I6Ylt242P84KdhCyVErnG+N8T0/JRr2d8rQas3h/11K9ev3ybDhZ67atkCRcSqVu3JZJaHLVCtdY4PmV9o7YSKIrTUYCqUceCR1y4cifDk6cbHkUO4zLXfte6ZIixIKRQrGCnImBTWUtQQ4w1Snm5UUk2lNMHGD0mbeDg/Q3SmF0LEtydcCcg2nDh/87rCGyoyZQa3C39CVjyGCbBGCFLhShJ3RsFmHUILshrJM1LXFRSxL0ykwPSxcT6WTz7930/OiJ4qmD8okn/waAr6JHI6g/xAAAybyNZo+g8uRWTnhWJ6bg9D0vJ3Td4EoFUJDZb813NFGRpysWu3ynjREsyzHLHHI+fKkxnSDrng7lM3tqEQjGazyeIzQEWLqeNaQRcyTZ4QcCcm8QNTbHLKNApIMMOflgEVlgwndrA4CNgmUUnl3oDp+yRZ44Dc2zXwbSih1/wkX+OZx3Y3C6zuBmQ3LippmWk+bjlqAvAzK96YRHxaDsImZqpwjOZkijiUOsjgEzs41hlQ9f6ONB5pPTlz8mpfmYe2OLhMIlU6NutnWjV1xeNWGesjmd6Y9RjnEquitAFwTqj8edE681WbFmDXv2foX8Apbn3GAgcs4SHiK/vApOB/T/HBIYw1ud5YUtkz9MlZIlDvkgg=
  on:
    branch: master
    tags: true
    python: "3.5"
  distributions: sdist bdist_wheel
  skip_cleanup: true
  skip_upload_docs: true